name: fudis-core
services:
  core-storybook:
    build:
      context: ./core/
    image: core
    container_name: core-storybook
    tty: true
    ports:
      - "6007:6007"
    volumes:
      - ./core/src:/usr/src/app/src
      - ./core/_index.scss:/usr/src/app/_index.scss
