name: Publish landing page from PR

on:
  push:
    paths:
      - "landing-page/**"
    branches-ignore:
      - main
      - "release-**"

jobs:
  publish:
    name: Publish PR landing page to AWS
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Start landing page deployment
        id: deployment
        uses: actions/github-script@v8
        with:
          script: |
            const envName = `Landing page for branch ${context.ref.replace('refs/heads/', '')}`;

            const { data } = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              environment: envName,
              description: `Landing page deploy for ${context.ref}`,
              auto_merge: false,
              required_contexts: [],
              transient_environment: true,
              production_environment: false
            });

            core.setOutput('deployment_id', String(data.id));
            core.setOutput('environment', envName);
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Copy landing page to S3 bucket
        run: aws s3 sync landing-page s3://${{ vars.AWS_S3_BUCKET_NAME }}/landing-page/branch/${{ github.ref_name }} --delete --cache-control max-age=5
      - name: Finish landing page deployment
        if: always() && steps.deployment.outputs.deployment_id
        uses: actions/github-script@v8
        env:
          JOB_STATUS: ${{ job.status }}
        with:
          script: |
            const map = {
              success: 'success',
              failure: 'failure',
              cancelled: 'error'
            };
            const state = map[process.env.JOB_STATUS] ?? 'error';

            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: Number('${{ steps.deployment.outputs.deployment_id }}'),
              state,
              environment: '${{ steps.deployment.outputs.environment }}',
              environment_url: 'https://fudis.funidata.fi/landing-page/branch/${{ github.ref_name }}/index.html',
              log_url: `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
              description: `Landing page deployment finished with ${process.env.JOB_STATUS}`
            });
