name: Run tests

on:
  # Enable reusing this workflow.
  workflow_call:
  # Run after PR is merged to main.
  push:
    branches:
      - main
  # Run for PR's. External PR's require approval before running checks.
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    name: Build image
    uses: ./.github/workflows/build_image.yaml

  stylelint:
    name: Lint styles
    needs:
      - build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: fudis-core
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/fudis-core.image.tar
      - name: Run stylelint
        run: docker run -t fudis-core npm run stylelint

  formatting:
    name: Check formatting
    needs:
      - build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: fudis-core
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/fudis-core.image.tar
      - name: Run prettier
        run: docker run -t fudis-core npm run format:check

  vr-tests:
    name: VR tests
    needs:
      - build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: fudis-core
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/fudis-core.image.tar
      - name: Start Storybook
        run: docker run -d -p 6007:6007 --workdir /usr/src/app/core fudis-core bash -c "npm run build:dist && npx storybook dev -p 6007 --no-open"
      - name: Build Playwright image
        run: docker build -t fudis-core-pw tests/
      - name: Wait for Storybook server to be up
        run: curl --head -X GET --retry 10 --retry-connrefused --retry-delay 5 http://localhost:6007
      - name: Create test output directories for mounts
        run: mkdir tests/test-results tests/playwright-report
      - name: Run visual regression tests
        run: |
          docker run -t \
            -e CI=true \
            -e PLAYWRIGHT_BASE_URL=http://localhost:6007 \
            --network=host \
            --mount type=bind,source=./tests/test-results,target=/usr/src/app/test-results \
            --mount type=bind,source=./tests/playwright-report,target=/usr/src/app/playwright-report \
            fudis-core-pw
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: tests/playwright-report/
          retention-days: 7
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results
          path: tests/test-results/
          retention-days: 7
