name: Run tests

on:
  # Enable reusing this workflow.
  workflow_call:
  # Run after PR is merged to main.
  push:
    branches:
      - main
  # Run for PR's. External PR's require approval before running checks.
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    name: Build image
    uses: ./.github/workflows/build_image.yaml

  formatting:
    name: Check formatting
    needs:
      - build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: fudis-core
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/fudis-core.image.tar
      - name: Run prettier
        run: docker run -t fudis-core npm run format:check


